set_property IOSTANDARD LVCMOS18 [get_ports clk_100M]
set_property PACKAGE_PIN E3 [get_ports clk_100M]
set_property IOSTANDARD LVCMOS18 [get_ports _rst]
set_property PACKAGE_PIN N17 [get_ports _rst]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {_rst_IBUF}]

set_property IOSTANDARD LVCMOS18 [get_ports An]
set_property PACKAGE_PIN C9 [get_ports An[7]]
set_property PACKAGE_PIN C10 [get_ports An[6]]
set_property PACKAGE_PIN D10 [get_ports An[5]]
set_property PACKAGE_PIN C11 [get_ports An[4]]
set_property PACKAGE_PIN M17 [get_ports An[3]]
set_property PACKAGE_PIN J14 [get_ports An[2]]
set_property PACKAGE_PIN K13 [get_ports An[1]]
set_property PACKAGE_PIN P14 [get_ports An[0]]

set_property IOSTANDARD LVCMOS18 [get_ports res]
set_property PACKAGE_PIN F14 [get_ports res[7]]
set_property PACKAGE_PIN N14 [get_ports res[6]]
set_property PACKAGE_PIN J13 [get_ports res[5]]
set_property PACKAGE_PIN G13 [get_ports res[4]]
set_property PACKAGE_PIN F13 [get_ports res[3]]
set_property PACKAGE_PIN G14 [get_ports res[2]]
set_property PACKAGE_PIN M13 [get_ports res[1]]
set_property PACKAGE_PIN H14 [get_ports res[0]]