set_property IOSTANDARD LVCMOS18 [get_ports clk_100M]
set_property PACKAGE_PIN E3 [get_ports clk_100M]
set_property IOSTANDARD LVCMOS18 [get_ports _rst]
set_property PACKAGE_PIN N17 [get_ports _rst]
set_property IOSTANDARD LVCMOS18 [get_ports _key]
set_property PACKAGE_PIN V5 [get_ports _key]

set_property IOSTANDARD LVCMOS18 [get_ports Out]
set_property PACKAGE_PIN U6 [get_ports Out[7]]
set_property PACKAGE_PIN R5 [get_ports Out[6]]
set_property PACKAGE_PIN U7 [get_ports Out[5]]
set_property PACKAGE_PIN R6 [get_ports Out[4]]
set_property PACKAGE_PIN R7 [get_ports Out[3]]
set_property PACKAGE_PIN U8 [get_ports Out[2]]
set_property PACKAGE_PIN T8 [get_ports Out[1]]
set_property PACKAGE_PIN V9 [get_ports Out[0]]
